from .ar_discovery import AGENT_BLUEPRINT as AR_DISCOVERY_BLUEPRINT
from .legal_royalty import AGENT_BLUEPRINT as LEGAL_ROYALTY_BLUEPRINT
from .marketing_pr import AGENT_BLUEPRINT as MARKETING_PR_BLUEPRINT
from .virtual_manager import AGENT_BLUEPRINT as VIRTUAL_MANAGER_BLUEPRINT

ORG_CHART = [
    AR_DISCOVERY_BLUEPRINT,
    VIRTUAL_MANAGER_BLUEPRINT,
    MARKETING_PR_BLUEPRINT,
    LEGAL_ROYALTY_BLUEPRINT
]
